"""
Compliance Service — FMR-1 Draft Generation
Generates RBI-compliant Fraud Monitoring Return (FMR-1) draft reports
for auto-blocked transactions with fraud scores >= 0.90.
"""
import time
import io
from typing import Dict, Any, Optional

# In-memory compliance queue (production would use persistent storage)
compliance_queue: Dict[str, Any] = {}


async def generate_fmr1_draft(
    transaction: dict,
    fraud_score: float,
    graph_data: dict,
    llm_explanation: str,
) -> Optional[bytes]:
    """
    Generates an FMR-1 draft PDF for RBI compliance submission.
    In production, this uses reportlab to generate a proper PDF.
    For demo: generates a text-based report as bytes.
    """
    try:
        report_lines = [
            "=" * 72,
            "FRAUD MONITORING RETURN (FMR-1) — DRAFT",
            "Reserve Bank of India — Department of Payment and Settlement Systems",
            "=" * 72,
            "",
            f"Report Generated: {time.strftime('%Y-%m-%d %H:%M:%S IST')}",
            f"Report ID: FMR1-{transaction.get('transaction_id', 'UNKNOWN')}",
            f"Status: AUTO-GENERATED DRAFT — PENDING COMPLIANCE OFFICER REVIEW",
            "",
            "-" * 72,
            "SECTION 1: TRANSACTION DETAILS",
            "-" * 72,
            f"  Transaction ID:     {transaction.get('transaction_id', 'N/A')}",
            f"  Sender UPI:         {transaction.get('sender', 'N/A')}",
            f"  Receiver UPI:       {transaction.get('receiver', 'N/A')}",
            f"  Amount (INR):       ₹{transaction.get('amount', 0):,.2f}",
            f"  Timestamp:          {transaction.get('timestamp', 'N/A')}",
            f"  Device ID:          {transaction.get('device_id', 'N/A')}",
            f"  Device Age (days):  {transaction.get('device_age_days', 'N/A')}",
            f"  Account Age (days): {transaction.get('account_age_days', 'N/A')}",
            f"  Scenario:           {transaction.get('scenario', 'N/A')}",
            "",
            "-" * 72,
            "SECTION 2: FRAUD DETECTION SUMMARY",
            "-" * 72,
            f"  Fraud Score:        {fraud_score:.4f} ({fraud_score*100:.1f}%)",
            f"  Risk Tier:          {'CRITICAL' if fraud_score >= 0.90 else 'HIGH ALERT'}",
            f"  Action Taken:       AUTO-BLOCKED",
            f"  Model Used:         SatarkGAT Ensemble v2.1",
            f"  Detection Method:   Graph Neural Network (2-hop neighborhood analysis)",
            "",
            "-" * 72,
            "SECTION 3: GRAPH ANALYSIS",
            "-" * 72,
            f"  Associated Accounts: {len(graph_data.get('associated_accounts', []))}",
            f"  Hop Count:          {graph_data.get('hop_count', 'N/A')}",
            f"  Attack Pattern:     {graph_data.get('scenario', 'N/A')}",
            "",
            "  Associated UPI IDs:",
        ]

        for acc in graph_data.get("associated_accounts", []):
            report_lines.append(f"    - {acc}")

        report_lines.extend([
            "",
            "-" * 72,
            "SECTION 4: MODUS OPERANDI (AI-GENERATED)",
            "-" * 72,
            f"  {llm_explanation}",
            "",
            "-" * 72,
            "SECTION 5: COMPLIANCE NOTES",
            "-" * 72,
            "  • This report was auto-generated by SatarkAI v2.1",
            "  • Requires review by designated Compliance Officer before submission",
            "  • Reference: RBI Master Direction on Digital Payment Security Controls",
            "  • DPSS.CO.OD No.2115/06.08.005/2020-21",
            "",
            "=" * 72,
            "END OF FMR-1 DRAFT",
            "=" * 72,
        ])

        report_text = "\n".join(report_lines)
        return report_text.encode("utf-8")

    except Exception as e:
        print(f"FMR-1 generation error: {e}")
        return None


def get_fmr1_draft(transaction_id: str) -> Optional[dict]:
    """Retrieve a queued FMR-1 draft by transaction ID."""
    return compliance_queue.get(transaction_id)
